<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaFutbol [
    <!ELEMENT ligaFutbol (partido)>
    <!ELEMENT partido (local, visitante)>
    <!ELEMENT local (nombre, goles)>
    <!ELEMENT visitante (nombre, goles)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT goles (#PCDATA)>
]>

<ligaFutbol>
    <partido>
        <local>
            <nombre>Nottingham Presa</nombre>
            <goles>0</goles>
        </local>
        <visitante>
            <nombre>Inter de Mitente</nombre>
            <goles>1</goles>
        </visitante>
    </partido>
</ligaFutbol>