=== christianstar37/clase/Tema 3 - XML/ExU4-ChristianCastilloDíaz/Ejercicio2.dtd
<!-- 
Ejercicio 2.- Entrega en el archivo ejercicio2.dtd un dtd externo que 
valide el formato del documento xml que has creado en ejercicio1.
-->

<!ELEMENT hamburgueseria (pedido+)>

<!ELEMENT pedido (fecha, nombreCliente, direccion, productos, precio)>
<!ATTLIST pedido numero ID #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nombreCliente (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (unidades, subtotal)>
<!ATTLIST producto nombre CDATA #REQUIRED precioUnidad CDATA #REQUIRED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>

<!ELEMENT precio (iva, precioTotal)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT precioTotal (#PCDATA)>

=== christianstar37/clase/Tema 3 - XML/ExU4-ChristianCastilloDíaz/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hamburgueseria SYSTEM "ejercicio2.dtd">
<!-- 
Ejercicio1.- Entrega en el archivo ejercicio1.xml la siguiente especificación.

Crea un Documento bien formado  que represente el pedido a una hamburguesería.
Usa elementos o atributos según consideres apropiado (OBLIGATORIO AL MENOS UN ATRIBUTO).
* La información contenida es: 
    *número de pedido, atributo
    *fecha, elemento
    *nombre de cliente, elemento 
    *dirección del cliente  elemento
    * listado de productos( cada producto tendrá: nombre del producto, número de unidades, precio unitario, subtotal),
    * IVA aplicado,
    * total con impuestos.
-->

<hamburgueseria>
    <pedido numero='P012'>
        <fecha>24-12-2025</fecha>
        <nombreCliente>Christian</nombreCliente>
        <direccion>Calle Madreselva</direccion>
        <productos>
            <producto nombre='patatas fritas' precioUnidad='2,00'>
                <unidades>3</unidades>
                <subtotal>6,00</subtotal>
            </producto>
            <producto nombre='hamburguesa' precioUnidad='5,00'>
                <unidades>2</unidades>
                <subtotal>10,00</subtotal>
            </producto>
        </productos>
        <precio>
            <iva>1,60</iva>
            <precioTotal>17,60</precioTotal>
        </precio>
    </pedido>
</hamburgueseria>
