=== christianstar37/clase/Tema 3 - XML/Ejercicio 12.dtd
<!ELEMENT pedido (datosCliente, productos, precioTotal)>

<!ELEMENT datosCliente (nombre,direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (#PCDATA)>
<!ATTLIST producto num CDATA #REQUIRED>

<!ELEMENT precioTotal (#PCDATA)>

=== christianstar37/clase/Tema 3 - XML/Ejercicio 7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedido SYSTEM "Ejercicio 12.dtd">
<pedido>
    <datosCliente>
        <nombre>Christian</nombre>
        <direccion>Calle Garc√©s Herrera</direccion>
    </datosCliente>
    <productos>
        <producto num='1'>Hamburgues con queso</producto>
        <producto num='2'>Patatas fritas</producto>
        <producto num='1'>Fanta</producto>
    </productos>
    <precioTotal>11,95</precioTotal>
</pedido>
