<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autor, editorial, año)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT año (#PCDATA)>
]>
<biblioteca>
    <libro>
        <titulo>El Principito</titulo>
        <autor>Antoine de Saint-Exupéry</autor>
        <editorial>Gallimard</editorial>
        <año>1943</año>
    </libro>
    <libro>
        <titulo>Cien Años de Soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <editorial>Editorial Sudamericana</editorial>
        <año>1967</año>
    </libro>
</biblioteca>