=== christianstar37/clase/Tema 3 - XML/PracticasXML_CastilloDíazChristian/Ejercicio 3/Ej3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="expedientesAcademicos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="expediente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="nombreEstudiante" type="xs:string"/>
                            <xs:element name="modulos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="nombre" type="xs:string"/>
                                                <xs:attribute name="aprobado">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:boolean">
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="curso">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Primero"/>
                                                            <xs:enumeration value="Segundo"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== christianstar37/clase/Tema 3 - XML/PracticasXML_CastilloDíazChristian/Ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<expedientesAcademicos
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="Ej3.xsd">
    <expediente>
        <titulo>ASIR</titulo>
        <nombreEstudiante>Christian</nombreEstudiante>
        <modulos>
            <modulo nombre="Digitalizaci贸n" aprobado="true" curso="Primero"/>
            <modulo nombre="Programaci贸n multimedia y dispositivos m贸viles" aprobado="false" curso="Segundo"/>
        </modulos>
    </expediente>
    <expediente>
        <titulo>ASIR</titulo>
        <nombreEstudiante>Aitor</nombreEstudiante>
        <modulos>
            <modulo nombre="Digitalizaci贸n" aprobado="false" curso="Primero"/>
        </modulos>
    </expediente>
</expedientesAcademicos>
